<a href="https://colab.research.google.com/github/palak00007/ml-lab/blob/main/ml_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
lst1=[1,2,3]
array1 = np.array(lst1)

In [ ]:
type(lst1)

list

In [ ]:

type(array1)

numpy.ndarray

In [ ]:
lst2=[10,11,12]
array2 = np.array(lst2)

In [ ]:
print(f"Adding two lists {lst1} and {lst2} together: {lst1+lst2}")

Adding two lists [1, 2, 3] and [10, 11, 12] together: [1, 2, 3, 10, 11, 12]


In [ ]:
print(f"Adding two numpy arrays {array1} and {array2} together: {array1+array2}")

Adding two numpy arrays [1 2 3] and [10 11 12] together: [11 13 15]


In [ ]:
print("array2 multiplied by array1: ",array1*array2)
print("array2 divided by array1: ",array2/array1)
print("array2 raised to the power of array1: ",array2**array1)

array2 multiplied by array1:  [10 22 36]
array2 divided by array1:  [10.   5.5  4. ]
array2 raised to the power of array1:  [  10  121 1728]


In [ ]:
# sine function
print("Sine: ",np.sin(array1))
# logarithm
print("Natural logarithm: ",np.log(array1))
print("Base-10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
# Exponential
print("Exponential: ",np.exp(array1))

Sine:  [0.84147098 0.90929743 0.14112001]
Natural logarithm:  [0.         0.69314718 1.09861229]
Base-10 logarithm:  [0.         0.30103    0.47712125]
Base-2 logarithm:  [0.        1.        1.5849625]
Exponential:  [ 2.71828183  7.3890561  20.08553692]


In [ ]:
print("A series of zeroes:",np.zeros(7))
print("A series of ones:",np.ones(9))
print("A series of numbers:",np.arange(5,16))
print("Numbers spaced apart by 2:",np.arange(0,11,2))
print("Numbers spaced apart by float:",np.arange(0,11,2.5))
print("Every 5th number from 30 in reverse order: ",np.arange(30,-1,-5))
print("11 linearly spaced numbers between 1 and 5: ",np.linspace(1,5,11))

A series of zeroes: [0. 0. 0. 0. 0. 0. 0.]
A series of ones: [1. 1. 1. 1. 1. 1. 1. 1. 1.]
A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]
Numbers spaced apart by 2: [ 0  2  4  6  8 10]
Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]
Every 5th number from 30 in reverse order:  [30 25 20 15 10  5  0]
11 linearly spaced numbers between 1 and 5:  [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------


In [ ]:
my_tuple = np.array([(1.5,2,3), (4,5,6)])
mat_tuple = np.array(my_tuple)
print (mat_tuple)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [ ]:
print("Dimension of this matrix: ",mat.ndim,sep='')
print("Size of this matrix: ", mat.size,sep='')
print("Shape of this matrix: ", mat.shape,sep='')
print("Data type of this matrix: ", mat.dtype,sep='')

Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [ ]:
print("Vector of zeros: ",np.zeros(5))
print("Matrix of zeros: ",np.zeros((3,4)))
print("Vector of ones: ",np.ones(4))
print("Matrix of ones: ",np.ones((4,2)))
print("Matrix of 5’s: ",5*np.ones((3,3)))
print("Identity matrix of dimension 2:",np.eye(2))
print("Identity matrix of dimension 4:",np.eye(4))
print("Random matrix of shape (4,3):\n",np.random.randint(low=1,high=10,size=(4,3)))

Vector of zeros:  [0. 0. 0. 0. 0.]
Matrix of zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Vector of ones:  [1. 1. 1. 1.]
Matrix of ones:  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix of 5’s:  [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
Identity matrix of dimension 2: [[1. 0.]
 [0. 1.]]
Identity matrix of dimension 4: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random matrix of shape (4,3):
 [[1 4 5]
 [9 8 3]
 [6 3 7]
 [2 8 2]]


In [ ]:
a = np.random.randint(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [ ]:
print("\na looks like:\n",a)
print("\nb looks like:\n",b)
print("\nc looks like:\n",c)



a looks like:
 [61 47 82 64 42 91 27 57 31 40 91 21 79 21  1 52 12 99  3 48 82 36 36 17
 50 78  9 33  3 23]

b looks like:
 [[[61 47 82 64 42]
  [91 27 57 31 40]
  [91 21 79 21  1]]

 [[52 12 99  3 48]
  [82 36 36 17 50]
  [78  9 33  3 23]]]

c looks like:
 [[61 47 82 64 42]
 [91 27 57 31 40]
 [91 21 79 21  1]
 [52 12 99  3 48]
 [82 36 36 17 50]
 [78  9 33  3 23]]


In [ ]:
b_flat = b.ravel()
print(b_flat)

[61 47 82 64 42 91 27 57 31 40 91 21 79 21  1 52 12 99  3 48 82 36 36 17
 50 78  9 33  3 23]


In [ ]:
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:4])
print("Elements from last backwards are:", arr[-1::-1])
print("3 Elements from last backwards are:", arr[-1:-6:-2])

arr2 = np.arange(0,21,2)
print("New array:",arr2)
print("Elements at 2nd, 4th, and 9th index are:", arr2[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
3 Elements from last backwards are: [10  8  6]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [ ]:
mat = np.random.randint(10,100,15).reshape(3,5)
print("Matrix of random 2-digit numbers\n",mat)

print("\nDouble bracket indexing\n")
print("Element in row index 1 and column index 2:", mat[1][2])

print("\nSingle bracket with comma indexing\n")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n")

print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

print("\nSubsetting sub-matrices\n")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix of random 2-digit numbers
 [[23 69 62 19 93]
 [57 42 69 91 99]
 [84 48 95 34 21]]

Double bracket indexing

Element in row index 1 and column index 2: 69

Single bracket with comma indexing

Element in row index 1 and column index 2: 69

Row or column extract

Entire row at index 2: [84 48 95 34 21]
Entire column at index 3: [19 91 34]

Subsetting sub-matrices

Matrix with row indices 1 and 2 and column indices 3 and 4
 [[91 99]
 [34 21]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[69 19]
 [42 91]]


In [ ]:
mat = np.random.randint(10,100,15).reshape(3,5)
print("Matrix of random 2-digit numbers\n",mat)
print ("\nElements greater than 50\n", mat[mat>50])

Matrix of random 2-digit numbers
 [[90 97 39 63 15]
 [36 11 12 29 22]
 [98 47 17 50 46]]

Elements greater than 50
 [90 97 63 98]


In [ ]:
mat>50

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True, False, False]])

In [ ]:
mat*(mat>50)

array([[90, 97,  0, 63,  0],
       [ 0,  0,  0,  0,  0],
       [98,  0,  0,  0,  0]])

In [ ]:
mat1 = np.random.randint(1,10,9).reshape(3,3)
mat2 = np.random.randint(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n",mat2)

print("\nAddition\n", mat1+mat2)
print("\nMultiplication\n", mat1*mat2)
print("\nDivision\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n", 3*mat1-2*mat2)

print("\nAddition of a scalar (100)\n", 100+mat1)

print("\nExponentiation, matrix cubed here\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
 [[6 6 2]
 [7 4 2]
 [7 4 2]]

2nd Matrix of random single-digit numbers
 [[8 3 9]
 [4 3 2]
 [9 7 4]]

Addition
 [[14  9 11]
 [11  7  4]
 [16 11  6]]

Multiplication
 [[48 18 18]
 [28 12  4]
 [63 28  8]]

Division
 [[0.75       2.         0.22222222]
 [1.75       1.33333333 1.        ]
 [0.77777778 0.57142857 0.5       ]]

Lineaer combination: 3*A - 2*B
 [[  2  12 -12]
 [ 13   6   2]
 [  3  -2  -2]]

Addition of a scalar (100)
 [[106 106 102]
 [107 104 102]
 [107 104 102]]

Exponentiation, matrix cubed here
 [[216 216   8]
 [343  64   8]
 [343  64   8]]

Exponentiation, sq-root using pow function
 [[2.44948974 2.44948974 1.41421356]
 [2.64575131 2.         1.41421356]
 [2.64575131 2.         1.41421356]]


In [ ]:
import pandas as pd


In [ ]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}


In [ ]:
s1=pd.Series(data=my_data)
print(s1)

0    10
1    20
2    30
dtype: int64


In [ ]:
s2=pd.Series(data=my_data, index=labels)
print(s2)

a    10
b    20
c    30
dtype: int64


In [ ]:
s3=pd.Series(arr, labels)
print(s3)

a    10
b    20
c    30
dtype: int64


In [ ]:
s4=pd.Series(d)
print(s4)

a    10
b    20
c    30
dtype: int64


In [ ]:
matrix_data = np.random.randint(1,20,size=20).reshape(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe data frame looks like\n",'-'*45, sep='')
print(df)


The data frame looks like
---------------------------------------------
    W   X   Y   Z
A  14   2  15   9
B  12  13  12  10
C  19  18   5   5
D  12   1   5  13
E  19  18  19  15


In [ ]:
d={'a':[10,20],'b':[30,40],'c':[50,60]}
df2=pd.DataFrame(data=d,index=['X','Y'])
print(df2)

    a   b   c
X  10  30  50
Y  20  40  60
